/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrameworkShadcnRouteImport } from './routes/framework/shadcn'
import { Route as FrameworkPrivacyRouteImport } from './routes/framework/privacy'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkShadcnRoute = FrameworkShadcnRouteImport.update({
  id: '/framework/shadcn',
  path: '/framework/shadcn',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkPrivacyRoute = FrameworkPrivacyRouteImport.update({
  id: '/framework/privacy',
  path: '/framework/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/framework/privacy': typeof FrameworkPrivacyRoute
  '/framework/shadcn': typeof FrameworkShadcnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/framework/privacy': typeof FrameworkPrivacyRoute
  '/framework/shadcn': typeof FrameworkShadcnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/framework/privacy': typeof FrameworkPrivacyRoute
  '/framework/shadcn': typeof FrameworkShadcnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/framework/privacy'
    | '/framework/shadcn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/terms' | '/framework/privacy' | '/framework/shadcn'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/framework/privacy'
    | '/framework/shadcn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  FrameworkPrivacyRoute: typeof FrameworkPrivacyRoute
  FrameworkShadcnRoute: typeof FrameworkShadcnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework/shadcn': {
      id: '/framework/shadcn'
      path: '/framework/shadcn'
      fullPath: '/framework/shadcn'
      preLoaderRoute: typeof FrameworkShadcnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework/privacy': {
      id: '/framework/privacy'
      path: '/framework/privacy'
      fullPath: '/framework/privacy'
      preLoaderRoute: typeof FrameworkPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  FrameworkPrivacyRoute: FrameworkPrivacyRoute,
  FrameworkShadcnRoute: FrameworkShadcnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
